/* CMS Content */
export const FETCHED_CMS_DATA = 'FETCHED_CMS_DATA';

/* Settings */
export const SET_TIMER_COUNT = 'SET_TIMER_COUNT';

/* Add Timer */
export const EDIT_TIMER_ID = 'EDIT_TIMER_ID';
export const EDIT_TIMER_CONFIGS = 'EDIT_TIMER_CONFIGS';
export const UPDATE_TOTAL_TIMERS = 'UPDATE_TOTAL_TIMERS';
export const REMOVE_TIMER = 'REMOVE_TIMER';
export const SET_MODAL_VISIBILITY = 'SET_MODAL_VISIBILITY';
export const ADD_RUNNING_INTERVAL = 'ADD_RUNNING_INTERVAL';
export const REMOVE_RUNNING_INTERVAL = 'REMOVE_RUNNING_INTERVAL';
